### ISSUE TITLE
Data & cohort provider registration ID lifetime

### ISSUE THREAD

**Issue by michaelkleber** [MagniteEngineering/ProprietaryCohorts#10]
In this proposal you say

> The cohort provider records this cohortRegistrationId and domain to build a proprietary graph of browserIds and behaviors and returns a cohort ID to the browser.
> [...]
> Clients will automatically reset cohort provider registration IDs periodically to enhance privacy (at least every 30 days, but perhaps more frequently).

When I first read this, I assumed this meant the cohort ID would be based on all the domains in that behavior graph, so up to 30 days' worth of data.

But I believe that in today's Web Adv BG call, Tom Kershaw indicated that the cohort provider would instead store per-person information only for a matter of hours.

Could you clarify?

**Comment by brodrigu** [comment]
I understood Tom's statement to be as a response to a question about the Gateway proposal, not Proprietary Cohorts.

I believe the Proprietary Cohort functionality could have some value if the Cohort Provider Registration ID was reset after a few hours, but more research and discussion is needed before a more precise recommendation than "at least every 30 days" can be made.

**Comment by michaelkleber** [comment]
Ah, sorry, I was definitely having trouble tracking which comments were about which of the two proposals.

**Comment by brodrigu** [comment]
Yeah no worries, we sometimes mix up FLoC and TURTLEDOVE as well, as you have pointed out. : )
