### ISSUE TITLE
Collusion between publisher and Cohort Provider

### ISSUE THREAD

**Issue by michaelkleber** [MagniteEngineering/ProprietaryCohorts#13]
The privacy properties of this proposal rest on the Cohort Provider not being able to learn too much about the individual events that go into its per-user profile — for example, only learning the domain of each page visit.  This is how you "prevent any correlation between user identity and cohort registration ID."

But if I visit some site repeatedly, then it seems like the site gets to learn a collection of my activity over time, and can associate that with something like a first-party cookie.  And the Cohort Provider _also_ gets to learn a collection of my activity over time, associated with my Cohort Registration ID.

Now suppose a publisher and its Cohort Provider have a direct conversation, say at the end of each week, where the publisher says "For each person who visited my site, here is the set of behaviors I observed for them.  Which Cohort Registration IDs match that behavior?"  The set of behaviors could include the times at which each person visited the site, for example.

Even if each individual event is _k_-anonymous, a collection of many events is likely to be much more identifying.  Even if it's not unique, the Cohort Provider might be able to say "Here are the 10 possible Cohort Registration IDs for that behavior."  And if the publisher did the same thing next week, it would likely narrow down the list again.

Over time, this would let a publisher match their first-party cookie to the Cohort Provider's ID, and then join on that to match to the first-party cookie of everyone else in their cluster of sites.

Any idea how to modify the proposal to defend against this?  (Periodically resetting the cohort provider ID doesn't seem to help at all.)

**Comment by brodrigu** [comment]
While I think there may be a number of small tweaks to the existing proposal that could alleviate your concern, I rethought the approach in order to try to maximize the privacy and I believe I found a solution that is much better with similar advantages.

Changes are in #14 

The updated version is here: https://github.com/MagniteEngineering/ProprietaryCohorts/tree/client-side-classification

**Comment by michaelkleber** [comment]
Yes, I like it!  I agree, the on-device computation approach in #14 is a great way to address the concern in this Issue.
