### ISSUE TITLE
Confusion about privacy properties

### ISSUE THREAD

**Issue by michaelkleber** [MagniteEngineering/ProprietaryCohorts#2]
I see that you've copied large chunks of text from Chrome's [FLoC](https://github.com/jkarlin/floc) and [TURTLEDOVE](https://github.com/WICG/turtledove) proposals, including a bunch of claims about privacy properties.  But it seems to me that this proposal doesn't have some of the properties you copied over.  Two examples:

* The Benefits section says "Publishers cannot learn the interest groups of the people who visit them", a key property of TURTLEDOVE.  But the API Example Flow says "The browser stores this cohortId for eligible users and makes it available to the publisher via a JS API."  That's exactly the opposite of the stated goal.

* The Benefits section says "Advertisers cannot learn the browsing habits of specific people", a key property of both FLoC and TURTLEDOVE.  But the API Example Flow shows the browser sending the cohort provider a request that includes the domain and a unique cross-site ID, and the proposal notes that the "cohort provider can be any entity".  That seems like a way to let _anybody_ build a list of all the sites you visit.

To make things more understandable and internally consistent, could you go through and call out explicitly the places where you're making some different choice about what parties are allowed to get what information?  The mixed messages in different parts of the doc are making it hard for me to really evaluate what you've proposed.

**Comment by brodrigu** [comment]
@michaelkleber first, thank you for taking the time to review. I think I've parsed two points of confusion and a request for some more detail throughout the doc. I've found when working with github, it is easier for followers to parse when issues are called out independently, so I've taken the liberty of pulling these into  separate issues here:

> The Benefits section says "Publishers cannot learn the interest groups of the people who visit them", a key property of TURTLEDOVE. But the API Example Flow says "The browser stores this cohortId for eligible users and makes it available to the publisher via a JS API." That's exactly the opposite of the stated goal.

I have moved this to #3

> The Benefits section says "Advertisers cannot learn the browsing habits of specific people", a key property of both FLoC and TURTLEDOVE. But the API Example Flow shows the browser sending the cohort provider a request that includes the domain and a unique cross-site ID, and the proposal notes that the "cohort provider can be any entity". That seems like a way to let anybody build a list of all the sites you visit.

I have moved this to #4

> To make things more understandable and internally consistent, could you go through and call out explicitly the places where you're making some different choice about what parties are allowed to get what information? The mixed messages in different parts of the doc are making it hard for me to really evaluate what you've proposed.

I have moved this to #5

I will do my best to respond to each of these in their separate issues.

**Comment by michaelkleber** [comment]
Sure, that makes sense.  Apologies for lumping things together.
