### ISSUE TITLE
Clarification of benefit "Publishers cannot learn the interest groups of the people who visit them

### ISSUE THREAD

**Issue by brodrigu** [MagniteEngineering/ProprietaryCohorts#3]
In #2 @michaelkleber wrote:
> The Benefits section says "Publishers cannot learn the interest groups of the people who visit them", a key property of TURTLEDOVE. But the API Example Flow says "The browser stores this cohortId for eligible users and makes it available to the publisher via a JS API." That's exactly the opposite of the stated goal.

**Comment by brodrigu** [comment]
@michaelkleber

I originally considered that since the cohortID was generated based on aggregate user data and not specifically labelled that they would be distinct from what TURTLEDOVE considers an `interest group`. However, I realize after re-reading TURTLEDOVE that even FLoCKs could fall into the generic definition of 'interest group'. I will update the proposal.

**Comment by michaelkleber** [comment]
Got it, thank you.
