### ISSUE TITLE
Clarification of benefit "Advertisers cannot learn the browsing habits of specific people",

### ISSUE THREAD

**Issue by brodrigu** [MagniteEngineering/ProprietaryCohorts#4]
In #2 @michaelkleber wrote:
> The Benefits section says "Advertisers cannot learn the browsing habits of specific people", a key property of both FLoC and TURTLEDOVE. But the API Example Flow shows the browser sending the cohort provider a request that includes the domain and a unique cross-site ID, and the proposal notes that the "cohort provider can be any entity". That seems like a way to let anybody build a list of all the sites you visit.

**Comment by brodrigu** [comment]
@michaelkleber 

The key point of this proposal is that the cohort provider does not receive any user-identifying information. The cohort provider registration id is anonymized and must not be linked with any personally identifying information.

So while advertisers can learn generic browsing habits via this proposal, they would not be able to learn whose habits those are, nor be able to target those individuals.

Feel free to file a PR to improve the language if you feel it is misleading.

**Comment by michaelkleber** [comment]
Ah, so a cohort provider could get a list of every domain visited by person 12345, but they wouldn't know that person 12345 was me?

The painful history here is that this sort of pseudonymous data set doesn't work to protect privacy.  Recall the story of the Netflix Prize de-anonymization, cf. Narayanan and Shmatikov's "Robust De-anonymization of Large Sparse Datasets" (https://www.cs.cornell.edu/~shmat/netflix-faq.html).

**Comment by brodrigu** [comment]
certainly with large amounts of information and a limited number of unique users (such as in the netflix example) it is possible to de-anonymize. The browser could control for this and guarantee some k-anonymity by only sending data to the cohort provider once a certain threshold is passed (suppression) or by reducing amount of data sent (generalization) .
